file_format: "1"
id: swept
name: Swept
type: shield
url: https://github.com/AYM1607/swept-crkbd/
requires: [pro_micro]
exposes: [nice_view_header]
features:
  - keys
  - display
siblings:
  - swept_left
  - swept_right
